# docker-compose.yml
version: '3.8'

services:
  flashcard-service:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env 
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app 
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env 
    ports:
      - "5432:5432"
    networks:
      - app-network


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network


  # يمكنك إضافة API Gateway والخدمات الأخرى هنا لاحقًا

volumes:
  postgres_data:
  redis_data: 

networks:
  app-network:
    driver: bridge