version: '3.8'

services:
  user-service:
    container_name: user-service
    image: dockerhub-flask_live_app:1.0.0
    build: .
    command:  [ "flask", "run", "--host=0.0.0.0", "--port=5000"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - REDIS_HOST=redis  # إضافة متغير البيئة لعنوان Redis
      - REDIS_PORT=6379   # إضافة متغير البيئة لمنفذ Redis
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - .:/app



    depends_on:
      - db
      - redis  # إضافة الاعتماد على خدمة Redis


  db:
    container_name: user-service
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


  redis:
    container_name: user-service
    image: redis:6.2  # استخدام صورة Redis
    ports:
      - "6379:6379"  # تعيين منفذ Redis
volumes:
  pgdata: {}