version: '3.8'

services:
  user-service:
    container_name: user-service
    image: dockerhub-flask_live_app:1.0.0
    build: .
    command:  [ "flask", "run", "--host=0.0.0.0", "--port=5000"]
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - REDIS_HOST=redis  # إضافة متغير البيئة لعنوان Redis
      - REDIS_PORT=6379   # إضافة متغير البيئة لمنفذ Redis
      - DB_URL=mysql+pymysql://root:rootpassword@db:3306/mydatabase
    volumes:
      - .:/app



    depends_on:
      - db
      - redis  # إضافة الاعتماد على خدمة Redis


  db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    container_name: user-service
    image: redis:6.2  # استخدام صورة Redis
    ports:
      - "6379:6379"  # تعيين منفذ Redis
volumes:
  pgdata: {}